#spring:
#  # 데이터소스 설정
#  datasource:
#    # JDBC URL - ${변수명:기본값} 형식으로 환경변수 주입 가능
#    # - DB_HOST: 데이터베이스 서버 주소 (로컬: localhost, AWS: RDS 엔드포인트)
#    # - useSSL=false: SSL 비활성화 (개발환경, 운영에서는 true 권장)
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/scandeals?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: ${DB_USERNAME:scandeals}
#    password: ${DB_PASSWORD:scandeals09123}
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 2
#  
#  # Redis 설정
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      timeout: 3000ms
#      lettuce:
#        pool:
#          max-active: 8
#          max-idle: 8
#          min-idle: 2
#  
#  # OAuth 2.0 설정 (Google)
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope:
#              - email
#              - profile
#            redirect-uri: http://localhost:8080/login/oauth2/code/google
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
#            user-name-attribute: id
#
## JWT 설정
#jwt:
#  secret: ${JWT_SECRET:dev-secret-key-for-testing-minimum-256-bits-required-please-change-in-production}
#  access-token-validity: 1800000      # 30분 (1,800초 × 1,000ms)
#  refresh-token-validity: 1209600000  # 14일 (1,209,600초 × 1,000ms)
#
## Lambda 크롤러용 API Key
#crawler:
#  api-key: ${CRAWLER_API_KEY:dev-secret-key}
#
## Slack 알림 (선택)
#slack:
#  webhook:
#    url: ${SLACK_WEBHOOK_URL:}